### ISSUE TITLE
Keyvault - secrets - perf pipeline fails during `Run perf tests` after throwing RequestFailedException (status code 429) resulting in an error when trying to JSON serialization the results

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#5427]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3567886&view=logs&j=42ded549-05ee-5cdb-7ba7-7a948a0cc056&t=49e32a0b-4245-531b-0723-9d45113ffbd3&l=1584

> Azure.Sdk.Tools.PerfAutomation.ProcessResultException: Command '/mnt/vss/_work/1/s/build/sdk/keyvault/azure-security-keyvault-secrets/test/perf/azure-security-keyvault-secrets-perf GetSecret --parallel 4 --sync' failed with exit code 134

```text
2024-03-07T10:18:20.2867568Z === Test Setup ===
2024-03-07T10:18:20.2867775Z 
2024-03-07T10:18:20.2868186Z Standard Error:
2024-03-07T10:18:20.2868990Z terminate called after throwing an instance of 'Azure::Core::RequestFailedException'
2024-03-07T10:18:20.2869664Z   what():  Received an HTTP unsuccessful status code: 429
2024-03-07T10:18:20.2869937Z 
2024-03-07T10:18:20.2870106Z 
2024-03-07T10:18:20.2871400Z    at Azure.Sdk.Tools.PerfAutomation.Util.RunAsync(String filename, String arguments, String workingDirectory, IDictionary`2 environmentVariables, StringBuilder outputBuilder, StringBuilder errorBuilder, Boolean throwOnError) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Util.cs:line 84
2024-03-07T10:18:20.2873466Z    at Azure.Sdk.Tools.PerfAutomation.Cpp.RunAsync(String project, String languageVersion, String primaryPackage, IDictionary`2 packageVersions, String testName, String arguments, Boolean profile, String profilerOptions, Object context) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Cpp.cs:line 174
2024-03-07T10:18:20.2875391Z    at Azure.Sdk.Tools.PerfAutomation.Program.RunPackageVersion(Options options, String service, String project, String primaryPackage, IDictionary`2 packageVersions, IEnumerable`1 tests, String outputJson, String outputCsv, String outputTxt, String outputMd, List`1 results) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs:line 353
2024-03-07T10:18:20.2876147Z 
2024-03-07T10:18:20.2890420Z CleanupAsync(azure-security-keyvault-secrets-perf)
2024-03-07T10:18:20.2891135Z 
2024-03-07T10:18:22.6392083Z [10:18:22.638] [/mnt/vss/_work/1/s] git checkout -- /mnt/vss/_work/1/s/vcpkg.json
2024-03-07T10:18:22.6466722Z Unhandled exception. System.ArgumentException: .NET number values such as positive and negative infinity cannot be written as valid JSON.
2024-03-07T10:18:22.6467674Z    at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueNotSupported()
2024-03-07T10:18:22.6468376Z    at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Double value)
2024-03-07T10:18:22.6469089Z    at System.Text.Json.Serialization.Converters.DoubleConverter.Write(Utf8JsonWriter writer, Double value, JsonSerializerOptions options)
2024-03-07T10:18:22.6469897Z    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6470877Z    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
2024-03-07T10:18:22.6471555Z    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6472298Z    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6472890Z    at System.Text.Json.Serialization.Converters.ListOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6473470Z    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6474189Z    at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6474985Z    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6475836Z    at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
2024-03-07T10:18:22.6476760Z    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
2024-03-07T10:18:22.6477916Z    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
2024-03-07T10:18:22.6478832Z    at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
2024-03-07T10:18:22.6479970Z    at Azure.Sdk.Tools.PerfAutomation.Program.WriteResults(String outputJson, String outputCsv, String outputTxt, String outputMd, List`1 results) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs:line 417
2024-03-07T10:18:22.6481258Z    at Azure.Sdk.Tools.PerfAutomation.Program.RunPackageVersion(Options options, String service, String project, String primaryPackage, IDictionary`2 packageVersions, IEnumerable`1 tests, String outputJson, String outputCsv, String outputTxt, String outputMd, List`1 results) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs:line 385
2024-03-07T10:18:22.6482359Z    at Azure.Sdk.Tools.PerfAutomation.Program.RunPackageVersion(Options options, String service, String project, String primaryPackage, IDictionary`2 packageVersions, IEnumerable`1 tests, String outputJson, String outputCsv, String outputTxt, String outputMd, List`1 results) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs:line 410
2024-03-07T10:18:22.6483169Z    at Azure.Sdk.Tools.PerfAutomation.Program.Run(Options options) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs:line 221
2024-03-07T10:18:22.6483844Z    at Azure.Sdk.Tools.PerfAutomation.Program.Main(String[] args) in /mnt/vss/_work/1/s/azure-sdk-tools/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/Program.cs:line 116
2024-03-07T10:18:22.6484320Z    at Azure.Sdk.Tools.PerfAutomation.Program.<Main>(String[] args)
2024-03-07T10:18:22.8788887Z 
2024-03-07T10:18:22.8843318Z ##[error]Bash exited with code '134'.
2024-03-07T10:18:22.8858341Z ##[section]Finishing: Run perf tests
```

**Comment by gearama** [comment]
429 means we are rate limited, just to know the error
